### ISSUE TITLE
White app window after what appears to be successful install

### ISSUE THREAD

**Issue by matthewclaussen** [Gustash/lutris_installers#19]
I ran the install through Lutris and it finishes successfully. When starting the app it loads into the app tray. After clicking on the app tray icon it brings up a white screen and I can't log in or do anything.

I see a few others on Youtube mention having the same issue in the last month.

What logs can I add to this ticket to help?

**Comment by Falkonsinger** [comment]
Same issue for me.. after successful installation, the program starts minimised to trey, opening it will just show a whitescreen…

**Comment by Victor-Baert** [comment]
maybe try to install wine 7.22 and ause that version, it's what I had to do

**Comment by matthewclaussen** [comment]
I was able to fix it by changing the Wine version for the Humble Games Collection to lutris-GE-Proton8-10-x86_64.
