### ISSUE TITLE
Humble Collection login fails 

### ISSUE THREAD

**Issue by Expressive-Synapse** [Gustash/lutris_installers#2]
(Forgive me if this isn't formatted properly im new at this)

Distro: Fedora36
Launcher: Lutris (native)
Browser: Firefox

The installer works correctly and humble collection opens. When I try to login it opens the window in firefox asking for permission but once permission is given the window will either close and not log me in or sometimes it doesn't do anything at all.

**Comment by Gustash** [comment]
What happens if you try running `xdg-open "humble://login?code=ABC&state=0"`?

What should happen is the humble app should give you a pop up telling you the auth is wrong

**Comment by Expressive-Synapse** [comment]
> What happens if you try running `xdg-open "humble://login?code=ABC&state=0"`?
> 
> What should happen is the humble app should give you a pop up telling you the auth is wrong

If by 'try running' you mean run it in the terminal I get the following result 

</home/Expressive_Synapse/Games/humble-games-collection/handle-humble-scheme: line 13: sqlite3: command not found
/home/Expressive_Synapse/.config/lutris/games/.yml does not exist. Exiting.
[Expressive_Synapse@fedora humble-games-collection]$>

and if I add it as an argument in lutris the game fails to launch. Sorry if this was not what you meant I've only been tinkering with linux for about a week.

**Comment by Gustash** [comment]
Are you sure you didn't actually install Lutris through Flatpak?

Does the folder `$HOME/.var/app/net.lutris.Lutris/config/lutris/games/` exist, for example?

**Comment by Expressive-Synapse** [comment]
> Are you sure you didn't actually install Lutris through Flatpak?
> 
> Does the folder `$HOME/.var/app/net.lutris.Lutris/config/lutris/games/` exist, for example?

The folder does exist yes, but that's because I tried to get the script to work with native and when that didn't work I tried the flatpak version, but since it also didn't work there I switched back to native.

**Comment by Gustash** [comment]
I've got a simplified version almost ready that should work for both native and flatpak. After work I'll push it up and tag you here so you can try it. Sorry about that

**Comment by Expressive-Synapse** [comment]
> I've got a simplified version almost ready that should work for both native and flatpak. After work I'll push it up and tag you here so you can try it. Sorry about that

No need to apologize, I really appreciate the work you've been doing and am thankful that you've been so quick to respond and help. Thank you.

**Comment by Gustash** [comment]
@Expressive-Synapse could you try [this](https://pastebin.com/x1q0SSFe) version and tell me if it works for you?

Keep in mind this version assumes you only have either native or flatpak Lutris installed. If you've got both, it will always try to use the Native version for login.

You should be able to just download the paste as "humble_collection.yml" and install like you would the previous version :)

**Comment by Expressive-Synapse** [comment]
> @Expressive-Synapse could you try [this](https://pastebin.com/x1q0SSFe) version and tell me if it works for you?
> 
> Keep in mind this version assumes you only have either native or flatpak Lutris installed. If you've got both, it will always try to use the Native version for login.
> 
> You should be able to just download the paste as "humble_collection.yml" and install like you would the previous version :)

This one worked great thank you!

**Comment by Gustash** [comment]
Awesome! Great to hear! Just waiting to hear from one of the Lutris moderators on whether this one can be accepted as an installer on lutris.net to update it here too
