### ISSUE TITLE
Humble Collection - Browser Window Does Not Open

### ISSUE THREAD

**Issue by Poisonsting** [Gustash/lutris_installers#9]
I've installed the Humble app using the latest version of your script on Lutris, the installation completes without error and the app launches, but a browser tab is never opened when I click "Sign In". I've tried restarting my Steam Deck over a dozen times, and have even tried changing the default browser to Chromium. Any ideas?

**Comment by Gustash** [comment]
What do you get if you run

```sh
xdg-mime query default x-scheme-handler/https
```

**Comment by Poisonsting** [comment]
`org.mozilla.firefox.desktop`

**Comment by Gustash** [comment]
Interesting... What do you get if you run

```sh
systemd-run --user --pipe env | grep ^PATH
```

**Comment by Poisonsting** [comment]
`Running as unit: run-u2261.service
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
`

**Comment by Gustash** [comment]
Can you paste me the logs for Humble from Lutris when you press the Sign In button? There should be a little dropdown next to the Play/Stop buttons in Lutris, with an option similar to "Show logs"

**Comment by Poisonsting** [comment]
```
lutris-wrapper: Humble Games Collection
Started initial process 73 from gamemoderun /home/deck/.var/app/net.lutris.Lutris/data/lutris/runners/wine/lutris-7.2-2-x86_64/bin/wine /home/deck/Games/humble-games-collection/start-humble.cmd --in-process-gpu
Start monitoring process.
gamemodeauto: 
fsync: up and running.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
File not found.

Initial process has exited (return code: 0)
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
```

**Comment by Gustash** [comment]
I don't see anything particularly wrong with your setup... have you tried reinstalling the app/lutris?

**Comment by Poisonsting** [comment]
I have tried reinstalling the app several times, but not Lutris. I've installed other apps in Lutris with no issues though.

Is there anything strange about the line `File not found.` in my logs?

**Comment by Gustash** [comment]
No, that's what the app start script logs if you don't have a .auth file in the `drive_c` directory of you prefix. Obviously for you, it won't be there, because it's not opening the browser.

Before anything else, I'd suggest trying to reinstall lutris, since other Steam Deck users have reported the install script working just fine for them

**Comment by Poisonsting** [comment]
Just reinstalled Lutris, no change.

**Comment by Poisonsting** [comment]
Which Wine runtime should I be using?

**Comment by Gustash** [comment]
It really shouldn't matter, but I've been successful with lutris-7.2.2 and lutris-7.2.2-fshack

**Comment by Poisonsting** [comment]
Neither work for me :(

Is there any other debugging we can try?

**Comment by Gustash** [comment]
I guess we can try this...

```sh
gio mime x-scheme-handler/https
```

What does that give you?

**Comment by Gustash** [comment]
Also, try closing Lutris and running it like this:

```sh
flatpak run --log-session-bus net.lutris.Lutris
```

Can you see lutris logs in your console if you do that?

**Comment by Poisonsting** [comment]
gio mime x-schmee-handler/https
```Default application for x-scheme-handler/https: org.mozilla.firefox.desktop
Registered applications:
        org.mozilla.firefox.deskotp
        com.github.Eloston.UngoogledChromium.dsektop
Recommended applications:
        org.mozilla.firefox.desktop
        com.github.Eloston.UngoogledChromium.desktop
```

When I run `flatpak run --log-session-bus net.lutris.Lutris` Humble opens as a black box, if at all.

**Comment by Poisonsting** [comment]
Reinstalling Humble again fixed the black box issue.

I recall running `xdg-mime default Humble-scheme-handler.desktop x-scheme-handler/humble
` on the recommendation of another guide, do you suppose it might pose an issue?

**Comment by Gustash** [comment]
The xdg-mime command would only apply after you've allowed access to your account from your browser, so that's not the problem. 

I'll be honest with you, I don't know what else to suggest. Everything you've sent seems to be in order, and I've heard from multiple Steam Deck users that everything works fine for them, so it must be a specific configuration you/something else has changed on your machine. 

I'll leave this issue open in case either you find a way to fix the problem, or someone else with the same problem can offer more debugging info. 

Sorry about this...

**Comment by spce-muffin** [comment]
I am  having the same issue (clicking Sign in button does not do anything). I have tried everything you have suggested here.

I can see logs in my console when I run `flatpak run --log-session-bus net.lutris.Lutris`, do you want me to post here what I get when I click the button or is there anything else you want me to check?

**Comment by Gustash** [comment]
> I am  having the same issue (clicking Sign in button does not do anything). I have tried everything you have suggested here.
> 
> 
> 
> I can see logs in my console when I run `flatpak run --log-session-bus net.lutris.Lutris`, do you want me to post here what I get when I click the button or is there anything else you want me to check?

If you could post those logs here, that would be great, thanks!

**Comment by spce-muffin** [comment]
I have attached the log file here! Line 474 is where I press the "Sign in" button.
[log.txt](https://github.com/Gustash/lutris_installers/files/9641046/log.txt)

**Comment by tommyfi** [comment]
This actually isn't an issue with your install @Gustash.  It's a steam deck specific issue.

On the steam deck, when switching between desktop mode and gaming mode currently there is an XDG error.  Basic solution is to run:
`systemctl restart --user xdg-desktop-portal`
between switches.  Longer explanation:

https://github.com/ValveSoftware/SteamOS/issues/775

**Comment by tommyfi** [comment]
Note: you can double check it's this behavior @spce-muffin and @Poisonsting by seeing if right clicking in lutris and saying view on lutris.net and it not opening a browser.  It's a general deck KDE issue and not this installer.

(note resetting the xdg-desktop-portal allowed it to open browsers in both cases)

**Comment by Gustash** [comment]
> This actually isn't an issue with your install @Gustash.  It's a steam deck specific issue.
> 
> 
> 
> On the steam deck, when switching between desktop mode and gaming mode currently there is an XDG error.  Basic solution is to run:
> 
> `systemctl restart --user xdg-desktop-portal`
> 
> between switches.  Longer explanation:
> 
> 
> 
> https://github.com/ValveSoftware/SteamOS/issues/775

That does make sense, I wasn't able to replicate this anywhere and I still haven't gotten my Steam Deck (hopefully ships this week!)

If anyone affected by this can verify that the workaround fixes the issue, I'll go ahead and close this issue. Hopefully Valve fixes this quickly upstream

**Comment by tommyfi** [comment]
Oh, to be clear, I was affected by the issue.  Just dug around a bit and found that solution.

**Comment by Poisonsting** [comment]
I can verify that `systemctl restart --user xdg-desktop-portal` fixed the issue for me!

**Comment by spce-muffin** [comment]
Worked for me as well! Thank you @tommyfi and @Gustash!

I think it is safe to close this issue

**Comment by Gustash** [comment]
Great news! I'll be closing this now then, enjoy your games :)

**Comment by recrudesce** [comment]
Just want to add another success story to this ticket - the fix detailed by tommyfi completely fixed my issue too.

Thanks for all the hard work finding out what caused the issue :)
